### ISSUE TITLE
New install.  Bot response cuts off around 350 character

### ISSUE THREAD

**Issue by MachineMonkey** [Paillat-dev/Botator#26]
If I prompt for completion, the bot will continue with text clearly generated in tandem with the first response but insist the first response was complete when challenged.
https://discord.com/channels/1077145366836813864/1077145366836813867/1077776979488673802

**Comment by Paillat-dev** [comment]
Did you try increasing the max tokens with the `/advanced` command?

**Comment by MachineMonkey** [comment]
Nope.  How do I do that?  Is there some command legend I can look up?

**Comment by MachineMonkey** [comment]
Duh... I just asked the interface how to do it.  Never mind and thanks for your time.

**Comment by MachineMonkey** [comment]
OK, well, that didn't work.  I increased my user token limit to 2000 and the bot just stopped typing about 300 characters in.  

• Introduction to Intensive Gardening 
Expand on this.  Take it step by step.
Botator
BOT
 — Today at 2:55 AM
Sure thing!
Introduction to Intensive Gardening: Intensive gardening is a gardening technique that involves utilizing the smallest amount of space with the most efficient use of resources. It is an efficient and sustainable way of producing a high yield of diverse produce such as fruits and vegetables. The main goals of intensive gardening are to

If I prompt it, it'll continue like it never stopped.  But only for another 300 characters.  Rinse and repeat.  What's going on here?

**Comment by Paillat-dev** [comment]
Could you please try putting that to something like 4096 with the /advanced command? If you need help there's the /advanced_help command:

> The maximum number of tokens to generate. Higher values will result in more coherent text, but will take longer to complete. (default: 200). Lower values will result in somentimes cutting off the end of the answer, but will be faster.

**Comment by MachineMonkey** [comment]
That seems to be working, though it rejected 4096 as invalid.  I did get it to accept 2000 and that seems to be working better.  New to discord.  Didn't realize it was prompting me like an ide.
